let response = {
    "BureauId": 6,
    "BureauProduct": {
        "BureauId": 6,
        "CategoryAlias": 0,
        "IsALL": false,
        "IsActive": false,
        "IsEnquiryCreated": false,
        "LOSId": 0,
        "Priority": 0,
        "ProductCode": "",
        "ProductId": 0,
        "RefNo": "0"
    },
    "Error": "Consumer record not found",
    "ErrorCode": "00",
    "ExistingRefNo": "0",
    "ReferenceNumber": "329317",
    "ResponseType": "Normal",
    "ResponseXML": {
        "BureauResponse": {
            "Request": {
                "Reference_Number": 329317,
                "Bureauid": 6,
                "LOS_Appln_Number": 285190003318,
                "Batch_Number": 0,
                "Product_Code": "",
                "Inquiry_Purpose": "Housing Loan",
                "Transaction_Amount": 20000,
                "First_Name": "Pratibha",
                "Last_Name": "Periwal",
                "AddrLine1": "2ND Street, GANDHINAGAR COLONY  CHINNA",
                "Locality1": "Haridwar",
                "City": "Haridwar",
                "State": "Tamil Nadu",
                "Postal": 625515,
                "DOB": "07-04-1980",
                "Gender": "Female",
                "Pan_Id": "BNEPD7841Q",
                "Mobile_Phone": 9345267895,
                "Status": "Finished",
                "TimeOutStatus": "NoHit",
                "FailureMessage": 0,
                "Priority": 1,
                "CreatedOn": "2019-06-26T00:00:00",
                "CreatedBy": 245399,
                "UpdatedOn": "2020-02-06T16:58:00",
                "UpdatedBy": "BureauAdmin",
                "IsBureauIterator": false,
                "Field1": ";;",
                "DurationOfAgreement": 12,
                "Field10": 7004,
                "LOS_Indicator": 3,
                "Serial_Number": 9876,
                "BureauCategory": {
                    "CategoryId": 0,
                    "IsEnabled": false
                },
                "IsOverrideRule": true,
                "IsCoolingPeriod": false,
                "AddressType": 2,
                "BureauCategory_Alias": 0,
                "Call_Type": "Synchronous",
                "DBSave": false,
                "RangeForExistingRequest": 0,
                "BureauProductList": "",
                "IsOverrideCoolingPeriodChk": false,
                "IsBureauPinging": false,
                "RequestType": "Normal",
                "CommSearchCriteria": "None",
                "LosIndex": "None",
                "IsEnquiryCreated": false,
                "MaxBureauCap": 0,
                "VerifyIdType": 0,
                "Age": 39,
                "FraudScore_Product": "",
                "FraudScore_Flag": "",
                "FraudScore_Classification": "",
                "AssetOriginalValue": "",
                "AssetValue": "",
                "TimeAtAddress": "",
                "PropertyType": "",
                "ResidentialStatus": "",
                "TimeAtAddress2": "",
                "PropertyType2": "",
                "ResidentialStatus2": "",
                "PrevAddresses": "",
                "EmailAddresses": "",
                "IdDocuments": "",
                "Employers": "",
                "Guarantors": "",
                "JointApplicantCompanies": "",
                "References": "",
                "JointApplicants": ""
            },
            "ErrorTypeDetails": {
                "ErrorType": {
                    "Reference_Number": 329317,
                    "BureauId": 6,
                    "ErrorCodeField": 0,
                    "ErrorMsg": "Consumer record not found",
                    "DetailsField": "Consumer record not found",
                    "CreatedOn": "2020-02-06T16:58:00"
                }
            },
            "InquiryResponseHeader": {
                "Reference_Number": 329317,
                "BureauId": 6,
                "CustomerCode": "MFI0000019",
                "ReportOrderNO": "ESAF200206CR353126384",
                "DATE_": "06-02-2020",
                "Time": "00:00:00",
                "HitCode": "SUCCESS",
                "CreatedOn": "0001-01-01T00:00:00",
                "ConsumerName": "ESAF"
            },
            "PersonalInfoDetails": {
                "PersonalInfo": {
                    "Reference_Number": 329317,
                    "Bureauid": 6,
                    "BureauCategoryId": 0,
                    "CreatedOn": "2020-02-06T16:58:00",
                    "MatchSeq": 0,
                    "Seq": 0,
                    "CompleteName": "",
                    "AdditionalNameDetails": ""
                }
            },
            "AddressInfoDetails": "",
            "IdentityInfoDetails": "",
            "TelephoneInfoDetails": "",
            "GroupDetails": "",
            "EmailAddressDetails": "",
            "AccountDetailsComplete": "",
            "History48MonthsDetails": "",
            "AccountSummaryDetails": {
                "AccountSummary": [
                    {
                        "Reference_Number": 329317,
                        "Bureuaid": 6,
                        "BureauCategoryId": 0,
                        "NoOfAccounts": 0,
                        "NoOfActiveAccounts": 0,
                        "NoOfWriteOffs": "",
                        "TotalPastDue": "",
                        "MostSevereStatusWithIn24Months": "",
                        "SingleHighestCredit": "",
                        "SingleHighestSanctionAmount": "",
                        "TotalHighCredit": "",
                        "AverageOpenBalance": "",
                        "SingleHighestBalance": "",
                        "NoOfPastDueAccounts": "",
                        "NoOfZeroBalanceAccounts": "",
                        "RecentAccount": "",
                        "OldestAccount": "",
                        "TotalBalanceAmount": "",
                        "TotalSanctionAmount": 0,
                        "TotalCreditLimit": "",
                        "TotalMonthlyPaymentAmount": "5552",
                        "OverDueAccounts": 0,
                        "CurrentBalances": 0,
                        "RecentAccntDateOpened": "",
                        "OldestAccntdateopened": "",
                        "CreditAccountDefault": "",
                        "CreditAccountClosed": "",
                        "CounterBalance": "",
                        "Outstanding_Balance_Secured": "",
                        "OUTSTANDING_BALANCE_SECURED_PE": "",
                        "Outstanding_Balance_UnSecured": "",
                        "OUTSTANDING_BALANCE_UNSECURED_": "",
                        "Accounttype": "",
                        "CreatedOn": "2020-02-06T16:58:00",
                        "Outstandingbalanceall": "",
                        "TotalWrittenOffAmount": "",
                        "CADSuitFiledCurrentBalance": "",
                        "LiveOrClosedIndicator": "",
                        "SecuredNumberOfAcounts": "",
                        "UnSecuredNumberOfAcounts": "",
                        "UntaggedNumberOfAccounts": "",
                        "DisbursedAmount": 0,
                        "MatchType": "Primary",
                        "NoOfSecuredAccounts": "",
                        "NoOfUnSecuredAccounts": "",
                        "NoOfUntaggedAccounts": ""
                    },
                    {
                        "Reference_Number": 329317,
                        "Bureuaid": 6,
                        "BureauCategoryId": 0,
                        "NoOfAccounts": 0,
                        "NoOfActiveAccounts": 0,
                        "NoOfWriteOffs": "",
                        "TotalPastDue": "",
                        "MostSevereStatusWithIn24Months": "",
                        "SingleHighestCredit": "",
                        "SingleHighestSanctionAmount": "",
                        "TotalHighCredit": "",
                        "AverageOpenBalance": "",
                        "SingleHighestBalance": "",
                        "NoOfPastDueAccounts": "",
                        "NoOfZeroBalanceAccounts": "",
                        "RecentAccount": "",
                        "OldestAccount": "",
                        "TotalBalanceAmount": "",
                        "TotalSanctionAmount": 0,
                        "TotalCreditLimit": "",
                        "TotalMonthlyPaymentAmount": "5259",
                        "OverDueAccounts": 0,
                        "CurrentBalances": 0,
                        "RecentAccntDateOpened": "",
                        "OldestAccntdateopened": "",
                        "CreditAccountDefault": "",
                        "CreditAccountClosed": "",
                        "CounterBalance": "",
                        "Outstanding_Balance_Secured": "",
                        "OUTSTANDING_BALANCE_SECURED_PE": "",
                        "Outstanding_Balance_UnSecured": "",
                        "OUTSTANDING_BALANCE_UNSECURED_": "",
                        "Accounttype": "",
                        "CreatedOn": "2020-02-06T16:58:00",
                        "Outstandingbalanceall": "",
                        "TotalWrittenOffAmount": "",
                        "CADSuitFiledCurrentBalance": "",
                        "LiveOrClosedIndicator": "",
                        "SecuredNumberOfAcounts": "",
                        "UnSecuredNumberOfAcounts": "",
                        "UntaggedNumberOfAccounts": "",
                        "DisbursedAmount": 0,
                        "MatchType": "Secondary",
                        "NoOfSecuredAccounts": "",
                        "NoOfUnSecuredAccounts": "",
                        "NoOfUntaggedAccounts": ""
                    }
                ]
            },
            "ScoreDetails": "",
            "EnquiryDetails": {
                "Enquiry": [
                    {
                        "Reference_Number": 329317,
                        "Bureauid": 6,
                        "DATE_": "11-10-2019",
                        "RequestPurpose": "OTHER",
                        "Amount": "6,000",
                        "CreatedOn": "2020-02-06T16:58:00",
                        "Disclaimer": "PRB",
                        "SeqNo": 0
                    },
                    {
                        "Reference_Number": 329317,
                        "Bureauid": 6,
                        "DATE_": "25-07-2019",
                        "RequestPurpose": "Other",
                        "Amount": "30,000",
                        "CreatedOn": "2020-02-06T16:58:00",
                        "Disclaimer": "MFI",
                        "SeqNo": 0
                    },
                    {
                        "Reference_Number": 329317,
                        "Bureauid": 6,
                        "DATE_": "10-09-2019",
                        "RequestPurpose": "OTHER",
                        "Amount": "6,000",
                        "CreatedOn": "2020-02-06T16:58:00",
                        "Disclaimer": "PRB",
                        "SeqNo": 0
                    },
                    {
                        "Reference_Number": 329317,
                        "Bureauid": 6,
                        "DATE_": "25-09-2019",
                        "RequestPurpose": "OTHER",
                        "Amount": "6,000",
                        "CreatedOn": "2020-02-06T16:58:00",
                        "Disclaimer": "PRB",
                        "SeqNo": 0
                    }
                ]
            },
            "TelecomResponseDetails": "",
            "PreScreenResponseDetails": "",
            "BureauAttributesDetails": "",
            "NonBureauAttributesDetails": "",
            "ResponseDataTypeDetails": "",
            "CreditReportSummaryDetails": "",
            "AdditionalDetailsInfo": "",
            "History24MonthsDetails": "",
            "IncomeEstimatorDetails": "",
            "DimensionalVariableDetails": "",
            "DisputeAndErrorRemarksDetails": "",
            "CAPSApplicantDetails": "",
            "IncomeDetails": "",
            "VariationsDetails": "",
            "AlertsDetails": {
                "Alert": {
                    "Reference_Number": 0,
                    "BureauId": 0,
                    "CreatedOn": "0001-01-01T00:00:00"
                }
            },
            "AccountSecurityDetailsComplete": "",
            "DerivedAttributesAccountSummary": {
                "Reference_Number": 329317,
                "BureauId": 6,
                "InquriesInLastSixMonths": 4,
                "LengthOfCreditHistoryYear": 0,
                "LengthOfCreditHistoryMonth": 0,
                "AverageAccountAgeYear": 0,
                "AverageAccountAgeMonth": 0,
                "NewAccountsInLastSixMonths": 0,
                "NewDelinqAccountInLastSixMonths": 0,
                "CreatedOn": "2020-02-06T16:57:44.803",
                "UpdatedOn": "2020-02-06T16:57:44.803"
            },
            "VerifyIdDetails": ""
        }
    },
    "Status": "Finished",
    "TimeOutStatus": "NoHit",
    "ScoreDetails": "",

}

let account_summary = response.ResponseXML.BureauResponse.AccountSummaryDetails
let total = 0;
console.log("Account_Summary", account_summary);
account_summary.AccountSummary.forEach((summary) => {
    total += Number(summary.TotalMonthlyPaymentAmount);
    console.log(total);

})
